/**
 * Unit tests for server/routers/auditLog.ts
 *
 * Covers all 5 procedure handler bodies:
 * - list: paginated audit logs with filters
 * - count: audit log count
 * - verifyIntegrity: hash chain verification
 * - byEntity: audit logs for a specific entity, filtered by org
 * - certificateInfo: platform certificate info
 */
import { describe, it, expect, vi, beforeEach } from "vitest";
import { appRouter } from "./index";
import type { TrpcContext } from "../_core/context";

// ==================== MOCKS ====================

vi.mock("../_core/env", () => ({
  ENV: {
    appUrl: "https://test.example.com",
    appId: "test-app",
    cookieSecret: "test-secret-key-minimum-32-chars!!",
    databaseUrl: "",
    isProduction: false,
    trustProxy: "false",
    forgeApiUrl: "",
    forgeApiKey: "",
    platformSigningPassphrase: "",
    piiEncryptionKey: "",
  },
}));

const mockGetAuditLogsPaginated = vi.fn().mockResolvedValue({
  logs: [
    { id: 1, eventType: "document.created", organizationId: 100 },
    { id: 2, eventType: "document.signed", organizationId: 100 },
  ],
  total: 2,
});
const mockGetAuditLogCount = vi.fn().mockResolvedValue(42);
const mockVerifyHashChainIntegrity = vi.fn().mockResolvedValue({
  totalRecords: 10,
  verifiedRecords: 10,
  brokenAt: null,
  isIntact: true,
});
const mockGetAuditLogsByEntity = vi.fn().mockResolvedValue([
  { id: 1, eventType: "document.created", organizationId: 100, entityType: "document", entityId: 5 },
]);
const mockGetCertificateInfo = vi.fn().mockReturnValue({
  subject: "CN=Hundredth Sign Platform",
  serialNumber: "1234567890",
  fingerprint: "AA:BB:CC:DD",
  notBefore: "2026-01-01T00:00:00Z",
  notAfter: "2031-01-01T00:00:00Z",
  isAutoGenerated: true,
});

vi.mock("../auditLog", () => ({
  appendAuditLog: vi.fn().mockResolvedValue({ id: 1, recordHash: "abc123" }),
  getAuditLogsByEntity: (...args: any[]) => mockGetAuditLogsByEntity(...args),
  getAuditLogsByOrg: vi.fn().mockResolvedValue([]),
  getAuditLogCount: (...args: any[]) => mockGetAuditLogCount(...args),
  getAuditLogsPaginated: (...args: any[]) => mockGetAuditLogsPaginated(...args),
  verifyHashChainIntegrity: (...args: any[]) => mockVerifyHashChainIntegrity(...args),
}));

vi.mock("../platformSignature", () => ({
  signPdfWithPlatformKey: vi.fn().mockResolvedValue(Buffer.from("platform-signed-pdf")),
  getCertificateInfo: (...args: any[]) => mockGetCertificateInfo(...args),
}));

vi.mock("../db", () => ({
  getDb: vi.fn().mockResolvedValue({}),
  getUserById: vi.fn().mockResolvedValue({ id: 1, openId: "test", name: "テスト", email: "test@example.com", isSuperAdmin: false }),
  getUserByEmail: vi.fn().mockResolvedValue(null),
  updateUserProfile: vi.fn().mockResolvedValue(undefined),
  createDocument: vi.fn().mockResolvedValue(1),
  getDocumentsByOrg: vi.fn().mockResolvedValue([]),
  getDocumentsByMultipleOrgs: vi.fn().mockResolvedValue([]),
  getDocumentById: vi.fn().mockResolvedValue(null),
  updateDocument: vi.fn().mockResolvedValue(undefined),
  deleteDocument: vi.fn().mockResolvedValue(undefined),
  upsertSignatureFields: vi.fn().mockResolvedValue(undefined),
  getSignatureFieldsByDocument: vi.fn().mockResolvedValue([]),
  createSignatureRequest: vi.fn().mockResolvedValue(1),
  createSignatureRequestsBulk: vi.fn().mockResolvedValue(undefined),
  getSignatureRequestsByDocument: vi.fn().mockResolvedValue([]),
  getSignatureRequestsByEmail: vi.fn().mockResolvedValue([]),
  getSignatureRequestsByEmailWithOrgFilter: vi.fn().mockResolvedValue([]),
  getSignatureRequestById: vi.fn().mockResolvedValue(null),
  getSignatureRequestByToken: vi.fn().mockResolvedValue(null),
  updateSignatureRequest: vi.fn().mockResolvedValue(undefined),
  checkAllSignersSigned: vi.fn().mockResolvedValue(false),
  getNextPendingSigner: vi.fn().mockResolvedValue(null),
  deleteSignatureRequestsByDocument: vi.fn().mockResolvedValue(undefined),
  createTemplate: vi.fn().mockResolvedValue(1),
  getTemplatesByOrg: vi.fn().mockResolvedValue([]),
  getTemplateById: vi.fn().mockResolvedValue(null),
  getPublicTemplates: vi.fn().mockResolvedValue([]),
  updateTemplate: vi.fn().mockResolvedValue(undefined),
  deleteTemplate: vi.fn().mockResolvedValue(undefined),
  incrementTemplateUsage: vi.fn().mockResolvedValue(undefined),
  upsertTemplateFields: vi.fn().mockResolvedValue(undefined),
  getTemplateFieldsByTemplate: vi.fn().mockResolvedValue([]),
  deepCopyTemplateToDocument: vi.fn().mockResolvedValue(1),
  getContactsByOrg: vi.fn().mockResolvedValue([]),
  getContactById: vi.fn().mockResolvedValue(null),
  createContact: vi.fn().mockResolvedValue(1),
  updateContact: vi.fn().mockResolvedValue(undefined),
  deleteContact: vi.fn().mockResolvedValue(undefined),
  createActivityLog: vi.fn().mockResolvedValue(undefined),
  getActivityLogsByDocument: vi.fn().mockResolvedValue([]),
  getRecentActivityByOrg: vi.fn().mockResolvedValue([]),
  getPublishedFaqs: vi.fn().mockResolvedValue([]),
  createFaq: vi.fn().mockResolvedValue(1),
  updateFaq: vi.fn().mockResolvedValue(undefined),
  deleteFaq: vi.fn().mockResolvedValue(undefined),
  createInquiry: vi.fn().mockResolvedValue(1),
  getInquiries: vi.fn().mockResolvedValue([]),
  updateInquiryStatus: vi.fn().mockResolvedValue(undefined),
  createEmailLog: vi.fn().mockResolvedValue(undefined),
  getDashboardStatsByOrg: vi.fn().mockResolvedValue({ totalDocuments: 0, pendingSignatures: 0, completedDocuments: 0, sentDocuments: 0, declinedDocuments: 0, draftDocuments: 0 }),
  getDocumentDetailByToken: vi.fn().mockResolvedValue(null),
  getPendingSignatureRequests: vi.fn().mockResolvedValue([]),
  getDocumentsNeedingReminder: vi.fn().mockResolvedValue([]),
  getDocumentsNeedingExpiration: vi.fn().mockResolvedValue([]),
  getDocumentsByMember: vi.fn().mockResolvedValue([]),
  getCategoriesByOrg: vi.fn().mockResolvedValue([]),
  createCategory: vi.fn().mockResolvedValue({ id: 1 }),
  updateCategory: vi.fn().mockResolvedValue(undefined),
  deleteCategory: vi.fn().mockResolvedValue(undefined),
  getGroupsByOrg: vi.fn().mockResolvedValue([]),
  createGroup: vi.fn().mockResolvedValue({ id: 1 }),
  updateGroup: vi.fn().mockResolvedValue(undefined),
  deleteGroup: vi.fn().mockResolvedValue(undefined),
  getGroupMembers: vi.fn().mockResolvedValue([]),
  addContactToGroup: vi.fn().mockResolvedValue(null),
  removeContactFromGroup: vi.fn().mockResolvedValue(undefined),
  getContactsByGroup: vi.fn().mockResolvedValue([]),
  getGroupsForContact: vi.fn().mockResolvedValue([]),
  claimSignatureRequestsByEmail: vi.fn().mockResolvedValue(0),
  claimInternalApprovalsByEmail: vi.fn().mockResolvedValue(0),
  getSignatureInboxEntriesForUser: vi.fn().mockResolvedValue([]),
  getInternalApprovalInboxEntriesForUser: vi.fn().mockResolvedValue([]),
  getOrganizationsByUser: vi.fn().mockResolvedValue([]),
  getOrganizationById: vi.fn().mockResolvedValue({
    id: 100, name: "Test Org", slug: "test-org", isActive: true,
    createdAt: new Date(), updatedAt: new Date(),
  }),
  getOrganizationBySlug: vi.fn().mockResolvedValue(null),
  updateOrganization: vi.fn().mockResolvedValue(undefined),
  createOrganization: vi.fn().mockResolvedValue(1),
  getMembership: vi.fn().mockResolvedValue({
    id: 1, userId: 1, organizationId: 100, role: "owner", isActive: true,
    createdAt: new Date(), updatedAt: new Date(),
  }),
  getMembershipsByOrg: vi.fn().mockResolvedValue([]),
  getMembershipIncludingInactive: vi.fn().mockResolvedValue(null),
  reactivateMembership: vi.fn().mockResolvedValue(undefined),
  getMemberUsageByOrg: vi.fn().mockResolvedValue([]),
  updateMembershipRole: vi.fn().mockResolvedValue(undefined),
  deactivateMembership: vi.fn().mockResolvedValue(undefined),
  createMembership: vi.fn().mockResolvedValue(1),
  countActiveMembers: vi.fn().mockResolvedValue(0),
  getActiveAllowedIps: vi.fn().mockResolvedValue([]),
  createAllowedIp: vi.fn().mockResolvedValue({ id: 1 }),
  deactivateAllowedIp: vi.fn().mockResolvedValue(undefined),
  createInternalApprovalsBulk: vi.fn().mockResolvedValue(undefined),
  getInternalApprovalsByDocument: vi.fn().mockResolvedValue([]),
  getInternalApprovalByToken: vi.fn().mockResolvedValue(null),
  updateInternalApproval: vi.fn().mockResolvedValue(undefined),
  deleteInternalApprovalsByDocument: vi.fn().mockResolvedValue(undefined),
  checkAllApproversApproved: vi.fn().mockResolvedValue(false),
  getNextPendingApprover: vi.fn().mockResolvedValue(null),
}));

vi.mock("../storage", () => ({
  storagePut: vi.fn().mockResolvedValue({ url: "https://example.com/file.pdf", key: "test-key" }),
  storageGet: vi.fn().mockResolvedValue({ url: "https://example.com/file.pdf", key: "test-key" }),
}));

vi.mock("../email", () => ({
  sendEmail: vi.fn().mockResolvedValue(true),
  buildSignatureRequestEmail: vi.fn().mockReturnValue({ subject: "署名依頼", html: "<p>test</p>" }),
  buildSignatureCompleteEmail: vi.fn().mockReturnValue({ subject: "署名完了", html: "<p>test</p>" }),
  buildAllSignedEmail: vi.fn().mockReturnValue({ subject: "全署名完了", html: "<p>test</p>" }),
  buildCcNotificationEmail: vi.fn().mockReturnValue({ subject: "写し通知", html: "<p>cc</p>" }),
  buildDeclinedEmail: vi.fn().mockReturnValue({ subject: "署名拒否", html: "<p>test</p>" }),
  buildInternalApprovalEmail: vi.fn().mockReturnValue({ subject: "approval", html: "<p>approval</p>" }),
  buildReminderEmail: vi.fn().mockReturnValue({ subject: "リマインダー", html: "<p>reminder</p>" }),
  resolveEmailLocale: vi.fn().mockImplementation((locale?: string) => locale || "ja"),
}));

vi.mock("../pdf", () => ({
  validatePdf: vi.fn().mockResolvedValue({ valid: true, pageCount: 3 }),
  embedSignaturesIntoPdf: vi.fn().mockResolvedValue(Buffer.from("signed-pdf")),
  generateSignedPdf: vi.fn().mockResolvedValue({ url: "https://example.com/signed.pdf", key: "signed-key" }),
  appendCompletionCertificate: vi.fn().mockResolvedValue(Buffer.from("signed-pdf-with-cert")),
  applyPdfPermissionLock: vi.fn().mockResolvedValue({ buffer: Buffer.from("locked-pdf"), locked: true }),
  SIGNATURE_FONTS: [{ id: "dancing-script", name: "Dancing Script", cssFamily: "'Dancing Script', cursive" }],
}));

vi.mock("../_core/notification", () => ({
  notifyOwner: vi.fn().mockResolvedValue(true),
}));

vi.mock("../stampService", () => ({
  generateStampDataUrl: vi.fn().mockReturnValue("data:image/png;base64,stamp-test"),
}));

vi.mock("../wormStorage", () => ({
  wormStorePdf: vi.fn().mockResolvedValue({ url: "https://example.com/worm/test.pdf", key: "worm/test.pdf", contentHash: "sha256-abc" }),
}));

// ==================== HELPERS ====================

const TEST_ORG_ID = 100;

type AuthenticatedUser = NonNullable<TrpcContext["user"]>;

function makeCtx(overrides: Partial<AuthenticatedUser> = {}, orgId = TEST_ORG_ID): TrpcContext {
  const user: AuthenticatedUser = {
    id: 1, openId: "test-user", email: "test@example.com", name: "テストユーザー",
    loginMethod: "manus", isSuperAdmin: false,
    createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date(),
    ...overrides,
  };
  return {
    user,
    req: {
      protocol: "https",
      headers: { "x-organization-id": String(orgId) },
      socket: { remoteAddress: "127.0.0.1" },
    } as any,
    res: { clearCookie: vi.fn() } as any,
  };
}

const caller = appRouter.createCaller(makeCtx());

// ==================== TESTS ====================

describe("auditLogRouter", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe("list", () => {
    it("returns paginated audit logs", async () => {
      const result = await caller.auditLog.list({ page: 1, pageSize: 50 });
      expect(result).toEqual({ logs: expect.any(Array), total: 2 });
      expect(mockGetAuditLogsPaginated).toHaveBeenCalledWith(
        expect.objectContaining({ organizationId: TEST_ORG_ID, page: 1, pageSize: 50 }),
      );
    });

    it("passes filter parameters to service", async () => {
      await caller.auditLog.list({
        eventType: "document.created",
        entityType: "document",
        startMs: 1000,
        endMs: 2000,
        page: 2,
        pageSize: 10,
      });
      expect(mockGetAuditLogsPaginated).toHaveBeenCalledWith(
        expect.objectContaining({
          organizationId: TEST_ORG_ID,
          eventType: "document.created",
          entityType: "document",
          startMs: 1000,
          endMs: 2000,
          page: 2,
          pageSize: 10,
        }),
      );
    });
  });

  describe("count", () => {
    it("returns audit log count for the organization", async () => {
      const result = await caller.auditLog.count();
      expect(result).toEqual({ count: 42 });
      expect(mockGetAuditLogCount).toHaveBeenCalledWith(TEST_ORG_ID);
    });
  });

  describe("verifyIntegrity", () => {
    it("returns hash chain verification result", async () => {
      const result = await caller.auditLog.verifyIntegrity();
      expect(result).toEqual({
        totalRecords: 10,
        verifiedRecords: 10,
        brokenAt: null,
        isIntact: true,
      });
      expect(mockVerifyHashChainIntegrity).toHaveBeenCalledWith(TEST_ORG_ID);
    });
  });

  describe("byEntity", () => {
    it("returns audit logs for a specific entity, filtered by org at DB level", async () => {
      const result = await caller.auditLog.byEntity({
        entityType: "document",
        entityId: 5,
        limit: 100,
      });
      // DB-level filtering: getAuditLogsByEntity receives orgId and filters in WHERE clause
      expect(result).toHaveLength(1);
      expect(result[0].organizationId).toBe(TEST_ORG_ID);
      expect(mockGetAuditLogsByEntity).toHaveBeenCalledWith("document", 5, TEST_ORG_ID, 100);
    });

    it("returns empty when no logs match org", async () => {
      mockGetAuditLogsByEntity.mockResolvedValueOnce([]);
      const result = await caller.auditLog.byEntity({
        entityType: "document",
        entityId: 99,
      });
      expect(result).toHaveLength(0);
    });
  });

  describe("certificateInfo", () => {
    it("returns platform certificate information", async () => {
      const result = await caller.auditLog.certificateInfo();
      expect(result).toEqual({
        subject: "CN=Hundredth Sign Platform",
        serialNumber: "1234567890",
        fingerprint: "AA:BB:CC:DD",
        notBefore: "2026-01-01T00:00:00Z",
        notAfter: "2031-01-01T00:00:00Z",
        isAutoGenerated: true,
      });
      expect(mockGetCertificateInfo).toHaveBeenCalled();
    });
  });
});
