/**
 * PDF Proxy Download Endpoint
 *
 * Decrypts AES-256-GCM encrypted PDFs stored in WORM storage and streams
 * them to the browser. For non-encrypted (legacy) records, fetches and
 * passes through the plaintext.
 *
 * Route: GET /api/pdf-proxy/:encodedKey?token=<hmac>
 *
 * Authentication is via a short-lived HMAC proxy token generated by the
 * tRPC download procedures (downloadSigned, downloadSignedByToken, etc.).
 */

import type { Express, Request, Response } from "express";
import { eq } from "drizzle-orm";
import { getDb } from "./db";
import { wormRecords } from "../drizzle/schema";
import { storageFetch } from "./storage";
import { verifyProxyToken, decryptPdf } from "./storageEncryption";

export function registerPdfProxyRoute(app: Express): void {
  app.get("/api/pdf-proxy/:encodedKey", async (req: Request, res: Response) => {
    try {
      const storageKey = decodeURIComponent(req.params.encodedKey);
      const token = req.query.token as string | undefined;

      // ── Auth: verify HMAC proxy token ──
      if (!token || !verifyProxyToken(storageKey, token)) {
        res.status(403).json({ error: "Invalid or expired download token" });
        return;
      }

      // ── Lookup worm_record for encryption metadata ──
      const db = await getDb();
      if (!db) {
        res.status(503).json({ error: "Database unavailable" });
        return;
      }

      const [record] = await db
        .select({
          encryptionIv: wormRecords.encryptionIv,
          encryptionTag: wormRecords.encryptionTag,
        })
        .from(wormRecords)
        .where(eq(wormRecords.storageKey, storageKey))
        .limit(1);

      if (!record) {
        res.status(404).json({ error: "WORM record not found" });
        return;
      }

      // ── Fetch raw bytes from storage ──
      const rawBuffer = await storageFetch(storageKey);

      // ── Decrypt if encrypted; pass through if legacy (NULL iv) ──
      let pdfBuffer: Buffer;
      if (record.encryptionIv && record.encryptionTag) {
        pdfBuffer = decryptPdf(rawBuffer, record.encryptionIv, record.encryptionTag);
      } else {
        pdfBuffer = rawBuffer;
      }

      // ── Stream plaintext PDF to browser ──
      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Length", pdfBuffer.length);
      res.setHeader("Cache-Control", "private, no-store");
      res.send(pdfBuffer);
    } catch (err: any) {
      console.error("[PdfProxy] Download failed:", err?.message ?? err);
      if (!res.headersSent) {
        res.status(500).json({ error: "PDF download failed" });
      }
    }
  });
}
